import Vue from 'vue'
import { Icon, Lazyload, badge, ImagePreview, RadioGroup, Radio, Tab, Tabs, Checkbox, Dialog, ActionSheet, Search, Swipe, SwipeItem, Grid, GridItem, Toast, Button, Switch, Rate, Tabbar, TabbarItem, NavBar } from 'vant'
Vue.use(Button)
Vue.use(NavBar)
Vue.use(Tabbar)
Vue.use(TabbarItem)
Vue.use(Rate)
Vue.use(Switch)
Vue.use(Icon)
Vue.use(Toast)
Vue.use(GridItem)
Vue.use(Grid)
Vue.use(SwipeItem)
Vue.use(Swipe)
Vue.use(Search)
Vue.use(ActionSheet)
Vue.use(Dialog)
Vue.use(Checkbox)
Vue.use(Tabs)
Vue.use(Tab)
Vue.use(Radio)
Vue.use(RadioGroup)
Vue.use(ImagePreview)
Vue.use(badge)
Vue.use(Lazyload)
